### ISSUE TITLE
VS Code questions

### ISSUE THREAD

**Issue by isidorn** [b4rtaz/voice-assistant#2]
Hi VS Code dev here 👋 

This extension looks pretty cool! Some questions:
1. We have a VS Code accessibility channel here https://gitter.im/Microsoft/vscode-a11y is it ok if I share this extension there and ask our community to provide feedback
2. We have this long standing issue https://github.com/microsoft/vscode/issues/40976 does it make sense that I share this extension there? Also if you are interested you can give that issue a read since it has a lot of user ideas what would make this experience great

Anyways, thanks a lot for working on this. And let me know if I can help somehow.
Isidor

**Comment by b4rtaz** [comment]
Hi! Thanks for the good words! 😄

1. Of course, if you think that fits into the channel.
2. I am not sure that my extensions resolves dictation support, but I believe that it could help many people. I'll look on this thread.
